name: Publish React.js website to CPANEL

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Build application ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        # FTP host
        server: ${{ secrets.FTP_SERVER }}
        # FTP user
        username: ${{ secrets.FTP_USERNAME }}
        # FTP password
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: "./build/"
        server-dir: "public_html/"
